version: '3'
services:
# redis:
#   image: "redis:5.0.4-alpine"
 sim:
   image: "mojaloop/mojaloop-simulator"
   # build: ../
   env_file: ./sim-backend.env
   ports:
     - "3000:3000"
     - "3001:3001"
     - "3003:3003"
 sim2:
   image: "mojaloop/mojaloop-simulator"
   # build: ../
   env_file: ./sim-backend2.env
   ports:
     - "3004:3000"
     - "3005:3001"
     - "3006:3003"
# scheme-adapter:
#   image: "mojaloop/sdk-scheme-adapter:latest"
#   env_file: ./scheme-adapter.env
#   ports:post
#     - "4000:4000"
#     - "4001:4001"
#   depends_on:
#     - redis